technology_dict = {
    "Advanced English": ["Advanced English", "English"],
    "Agile": ["Agile"],
    "AI": ["AI"],
    "Aiohttp": ["Aiohttp"],
    "Algorithms and Data Structures": ["Algorithms and Data Structures", "Data Structures"],
    "AWS": [
        "Amazon AWS",
        "AWS",
        "AWS Aurora",
        "AWS DynamoDB",
        "AWS Lambda",
        "AWS S3",
        "AWS Serverless Lambda",
        "AWS: Lambda"
    ],
    "Angular": ["Angular.js", "AngularJS"],
    "Apache Airflow": ["Apache Airflow"],
    "API": ["API"],
    "API Microsoft Graph": ["API Microsoft Graph"],
    "Apollo": ["Apollo"],
    "AR": ["AR"],
    "Architect": ["Architect"],
    "Ardupilot": ["Ardupilot"],
    "Astapi": ["Astapi"],
    "Asyncio": ["Asyncio"],
    "Automation": ["Automation", "Data Engineering"],
    "Back-end": ["Back-end"],
    "Backend Development": ["Backend Development"],
    "Beautifulsoup": ["Beautifulsoup"],
    "Big Data": ["Big Data", "Bigdata"],
    "Blockchain and Cryptocurrency": ["Blockchain and Cryptocurrency"],
    "C++": ["C++"],
    "CI/CD": ["CI/CD", "CI"],
    "Celery": ["Celery"],
    "ChatGPT": ["ChatGPT"],
    "Cloud": ["Cloud"],
    "Computer Science": ["Computer Science"],
    "CRM": ["CRM"],
    "CSS": ["CSS", "HTML & CSS"],
    "Data": ["Data"],
    "Data Extraction Engineer": ["Data Extraction Engineer"],
    "Data Research": ["Data Research"],
    "Data Science": ["Data Science", "ML", "Machine Learning"],
    "Data Scraping & Processing": ["Data Scraping & Processing"],
    "Data Warehouse": ["Data Warehouse"],
    "Databases": ["Databases", "Database"],
    "DevOps": ["DevOps"],
    "Django": ["Django"],
    "Django ORM": ["Django ORM"],
    "Django REST": [
        "Django REST",
        "Django REST API",
        "Django REST Framework",
        "DRF"
    ],
    "Docker": ["Docker", "Docker Compose"],
    "Fullstack": [
        "Full Stack",
        "Full-Stack Web Development",
        "Fullstack"
    ],
    "GCP": ["GCP", "Google Cloud Platform"],
    "HTML": ["HTML"],
    "Knowledge of SQL": ["Knowledge of SQL", "SQL"],
    "Kubernetes": ["Kubernetes", "Kubernetes (1+ years)"],
    "LoRa": ["LoRa"],
    "LoRaWAN": ["LoRaWAN"],
    "Low Code Developer": ["Low Code Developer"],
    "MariaDB": ["MariaDB"],
    "Matplotlib": ["Matplotlib"],
    "Microservices": [
        "Microservice Architecture",
        "Microservices"
    ],
    "MongoDB": ["MongoDB", "Mongo DB"],
    "MSSQL": ["MSSQL"],
    "MySQL": ["MySQL"],
    "Negotiation and Communication": ["Negotiation and Communication"],
    "Networking": ["Networking"],
    "Next.js": ["Next.js"],
    "Node.js": ["Node.js"],
    "Nonweb": ["Nonweb"],
    "NoSQL": ["NoSQL"],
    "NumPy": ["NumPy"],
    "Odoo": ["Odoo"],
    "OGR": ["OGR"],
    "OpenCV": ["OpenCV"],
    "OpenLDAP": ["OpenLDAP"],
    "OWL": ["OWL"],
    "Pandas": ["Pandas"],
    "PHP": ["PHP"],
    "PL": ["PL"],
    "Playwright": ["Playwright"],
    "PostgreSQL": ["Postgres", "PostgreSQL"],
    "Power Automate": ["Power Automate"],
    "Power Platform Developer": ["Power Platform Developer"],
    "PowerBI": ["PowerBI"],
    "Puppeteer": ["Puppeteer"],
    "PX4": ["PX4"],
    "PySpark": ["PySpark"],
    "Pytest": ["Pytest"],
    "Python": [
        "Python",
        "Python 3.8+",
        "Python3",
        "Python3+",
        "Pytorch"
    ],
    "QA Automation": ["QA Automation"],
    "Quantitative Research": [
        "Quant Researchers",
        "Quantitative Research"
    ],
    "R": ["R"],
    "RDBMS": ["RDBMS"],
    "React": ["React", "React Native", "React.js", "Reactjs", "Reactphp"],
    "Redis": ["Redis"],
    "Redux": ["Redux"],
    "Regular Expressions": ["Regular Expressions"],
    "REST": ["REST", "REST API", "RESTful API", "Rexep"],
    "Rust": ["Rust"],
    "SaaS": ["SaaS"],
    "Salesforce": ["Salesforce"],
    "Scala": ["Scala"],
    "Scikit-learn": ["Scikit-learn"],
    "SciPy": ["SciPy"],
    "Scraping": ["Scraping"],
    "Scrum": ["Scrum"],
    "Seaborn": ["Seaborn"],
    "Selenium": ["Selenium"],
    "Serverless": ["Serverless"],
    "Snowflake": ["Snowflake"],
    "SOTA": ["SOTA"],
    "SQLAlchemy": ["SQLAlchemy"],
    "SQLite": ["SQLite"],
    "Support": ["Support"],
    "Software Design": ["Software Design"],
    "Tabular Data": ["Tabular Data"],
    "Team Lead": ["Team Lead"],
    "Tensorflow": [
        "Tensorflow",
        "Tensorflow;",
        "Tensorrt"
    ],
    "Terraform": ["Terraform"],
    "Time-series": ["Time-series"],
    "TypeScript": ["TypeScript"],
    "UAV": ["UAV"],
    "Unit Testing": ["Unit Testing", "Unittest"],
    "Unix": ["Unix"],
    "VR": ["VR"],
    "Vue": ["Vue", "Vue.js"],
    "Web": ["Web"],
    "Web Scraping": ["Web Scraping", "Web Scrapping", "Web3"],
    "WordPress": ["WordPress"],
    "XML": ["XML"],
    "XR": ["XR"]
}